name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --all -- -Dwarnings
    - name: Format
      run: cargo fmt --all --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        OPENSHOCK_TOKEN: ${{ secrets.OPENSHOCK_TOKEN }}
        SHOCKER_TEST_ID: ${{ secrets.SHOCKER_TEST_ID }}
        USER_TEST_ID: ${{ secrets.USER_TEST_ID }}
